apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    kiamol: ch14
  name: timecheck
  namespace: mon1
spec:
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: timecheck
status:
  loadBalancer: {}
