---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timecheck
  namespace: mon1
  labels:
    kiamol: ch14
spec:
  selector:
    matchLabels:
      app: timecheck
  template:
    metadata:
      labels:
        app: timecheck
    spec:
      containers:
        - name: timecheck
          image: kiamol/ch07-timecheck
          env:
            - name: Metrics__Enabled
              value: "true"
          ports:
            - containerPort: 8080
              name: metrics
